spring.application.name=mbcBoard_spring
# 포트 설정
server.port=8888

spring.datasource.url=jdbc:mysql://192.168.0.144:3306/mbcBoard?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=mbcuser
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true